import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});
export const metadata = {
  title: {
    default: "DBlog",
    template: "%s | DBlog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}  antialiased`}>
        <Navbar></Navbar>
        <div className="min-h-[calc(100vh-113px)]">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
